services:
  initiator:
    build: .
    container_name: ike_initiator
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      vpn-net:
        ipv4_address: 10.200.200.2
    volumes:
      - ./initiator/swanctl.conf:/etc/swanctl/conf.d/swanctl.conf:ro
      - ./initiator/strongswan.conf:/etc/strongswan.conf:ro
      - ./initiator/capture:/usr/capture
      - ./initiator/setup-test.sh:/usr/bin/setup-test.sh
      - ./initiator/rekey-test.sh:/usr/bin/rekey-test.sh
      - ./initiator/tunnel-setup.sh:/usr/bin/tunnel-setup.sh

  responder:
    build: .
    container_name: ike_responder
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      vpn-net:
        ipv4_address: 10.200.200.3
    volumes:
      - ./responder/swanctl.conf:/etc/swanctl/conf.d/swanctl.conf:ro
      - ./responder/strongswan.conf:/etc/strongswan.conf:ro
      - ./responder/capture:/usr/capture
      - ./responder/setup-test.sh:/usr/bin/setup-test.sh
      - ./responder/rekey-test.sh:/usr/bin/rekey-test.sh
      - ./responder/tunnel-setup.sh:/usr/bin/tunnel-setup.sh

networks:
  vpn-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.200.0/24
