services:
  initiator:
    build: .
    container_name: ike_initiator
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      vpn-net:
        ipv4_address: 10.200.200.2
    volumes:
      - ./initiator/swanctl.conf:/etc/swanctl/conf.d/swanctl.conf:ro
      - ./initiator/capture:/usr/capture

  responder:
    build: .
    container_name: ike_responder
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      vpn-net:
        ipv4_address: 10.200.200.3
    volumes:
      - ./responder/swanctl.conf:/etc/swanctl/conf.d/swanctl.conf:ro
      - ./responder/capture:/usr/capture

networks:
  vpn-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.200.0/24
